"""Deterministic risk signal engine (M7).

Risk items are generated by RULES over canonical facts, derived metrics,
segment data and valuation outputs — never by an LLM and never guessed.
Each item carries:
- category (structural/cyclical/execution/financial/regulatory/valuation/concentration)
- severity (HIGH/MEDIUM/LOW) from explicit thresholds
- evidence: fact ids / series the signal is computed from
- monitoring: the next observable that would confirm or falsify the risk
"""

from __future__ import annotations

from equitylens.metrics.engine import MetricEngine


def _series(engine, company_id: str, metric: str, freq: str = "quarterly"):
    try:
        pts = engine.compute(metric, company_id, frequency=freq)
    except ValueError:
        return []
    return pts


def _yoy_change(vals: list[float | None]) -> float | None:
    vals = [v for v in vals if v is not None]
    if len(vals) < 2 or not vals[-1]:
        return None
    return vals[-1] / vals[-2] - 1.0


def _evs(points) -> list[str]:
    """Evidence IDs: canonical fact id, or the input lineage for derived metrics."""
    ids: list[str] = []
    for p in points:
        if p.canonical_fact_id:
            ids.append(p.canonical_fact_id)
        elif getattr(p, "input_fact_ids", None):
            ids.extend(p.input_fact_ids)
    return ids


def risk_signals(store, company_id: str, ticker: str) -> dict:
    engine = MetricEngine(store)
    risks: list[dict] = []
    checks: list[dict] = []

    def add(category, severity, title, desc, evidence_ids=None, monitoring=None, confidence="MEDIUM"):
        risks.append({
            "category": category, "severity": severity, "title": title, "description": desc,
            "evidence_ids": evidence_ids or [],
            "monitoring": monitoring or "下一份 10-K/10-Q 复核同一信号",
            "confidence": confidence, "generated_by": "deterministic-rules.v1",
        })

    def record_check(key, fn):
        """Run one risk module and record its coverage/failure explicitly.

        A module returns (status, reason, evidence_ids); an exception is a module
        ERROR and must never be silently swallowed as "checked".
        """
        try:
            status, reason, evidence_ids = fn()
        except Exception as exc:  # noqa: BLE001 - per-module isolation is the point
            status, reason, evidence_ids = "ERROR", str(exc), []
        checks.append({"key": key, "status": status, "reason": reason, "evidence_ids": evidence_ids})

    # ---- growth / execution ----
    def _growth():
        growth = _series(engine, company_id, "REVENUE_GROWTH_YOY")
        if len(growth) < 3:
            return "INCOMPLETE_PERIOD", "收入同比序列不足 3 个季度", []
        recent = [p.value for p in growth[-3:] if p.value is not None]
        if len(recent) < 2 or recent[-1] is None:
            return "INCOMPLETE_PERIOD", "收入同比缺失近期值", []
        decel = recent[-1] - recent[-2]
        if decel < -0.05:
            add("cyclical", "MEDIUM", "收入增速明显放缓",
                f"最近季度收入同比 {recent[-1]*100:.1f}%，较上季度 {recent[-2]*100:.1f}% 回落 {(recent[-2]-recent[-1])*100:.1f}pp。",
                evidence_ids=_evs(growth[-2:]),
                monitoring="未来 2 个季度的收入同比是否企稳")
        elif recent[-1] < 0.03:
            add("execution", "MEDIUM", "增长动能偏弱",
                f"最近季度收入同比仅 {recent[-1]*100:.1f}%（低于 3% 阈值）。",
                evidence_ids=_evs(growth[-1:]),
                monitoring="下季度收入同比是否回升至 3% 以上")
        return "OK", None, _evs(growth[-2:])
    record_check("growth", _growth)

    # ---- profitability ----
    def _profitability():
        opm = _series(engine, company_id, "OPERATING_MARGIN")
        if len(opm) < 5:
            return "INCOMPLETE_PERIOD", "营业利润率序列不足 5 个季度", []
        vals = [p.value for p in opm[-5:] if p.value is not None]
        if len(vals) < 3 or vals[-1] is None or not vals[0]:
            return "INCOMPLETE_PERIOD", "营业利润率缺失近期值", []
        delta = vals[-1] - vals[0]
        if delta < -0.02:
            add("financial", "MEDIUM", "营业利润率走低",
                f"营业利润率近 5 季从 {vals[0]*100:.1f}% 降至 {vals[-1]*100:.1f}%（{(vals[0]-vals[-1])*100:.1f}pp）。",
                evidence_ids=_evs(opm[-5:]),
                monitoring="下季度利润率能否止跌")
        return "OK", None, _evs(opm[-1:])
    record_check("profitability", _profitability)

    # ---- cash conversion / capital intensity (shared TTM contract) ----
    def _cash_flow():
        ocf = engine.current("OPERATING_CASH_FLOW", company_id, "ttm")
        if ocf.status != "OK":
            return ocf.status, ocf.missing_reason, []
        capex = engine.current("CAPITAL_EXPENDITURES", company_id, "ttm")
        if capex.status != "OK":
            return capex.status, capex.missing_reason, []
        evidence = list(ocf.input_fact_ids or []) + list(capex.input_fact_ids or [])
        if ocf.value and capex.value / ocf.value > 0.5:
            add("financial", "HIGH", "资本开支强度显著上升",
                f"TTM CapEx {capex.value/1e9:.0f}B 占 TTM 经营现金流 {ocf.value/1e9:.0f}B 的 {capex.value/ocf.value*100:.0f}%（>50% 阈值）。若新增资本回报不足，自由现金流转化将受压。",
                evidence_ids=evidence,
                monitoring="下季度 CapEx/OCF 比例与 FCF 转化率")
        return "OK", None, evidence
    record_check("cash_flow", _cash_flow)

    # ---- balance sheet ----
    def _balance_sheet():
        nd = _series(engine, company_id, "NET_DEBT")
        if not nd or nd[-1].value is None:
            return "INCOMPLETE_PERIOD", "净债务缺失", []
        net_debt = nd[-1].value
        fcf = engine.current("FCF", company_id, "ttm")
        if fcf.status != "OK":
            return fcf.status, fcf.missing_reason, []
        evidence = list(fcf.input_fact_ids or [])
        if nd[-1].canonical_fact_id:
            evidence.insert(0, nd[-1].canonical_fact_id)
        if net_debt > 0 and fcf.value:
            ratio = net_debt / fcf.value
            if ratio > 1.5:
                add("financial", "HIGH", "净债务相对自由现金流偏高",
                    f"净债务 {net_debt/1e9:.0f}B 是 TTM FCF {fcf.value/1e9:.0f}B 的 {ratio:.1f} 倍（>1.5x）。",
                    evidence_ids=evidence,
                    monitoring="下一期净债务与 FCF 比值")
        return "OK", None, evidence
    record_check("balance_sheet", _balance_sheet)

    # ---- valuation risk (data-driven, no market price needed) ----
    def _valuation():
        from equitylens.valuation.service import default_valuation

        dv = default_valuation(store, company_id, ticker)
        tv_share = dv["result"]["terminal_value_share"]
        evidence = sorted({
            fact_id
            for item in dv["assumptions"]["meta"].values()
            if isinstance(item, dict)
            for fact_id in (item.get("source_ids") or [])
        })
        if tv_share > 0.80:
            add("valuation", "MEDIUM", "DCF 价值对终值假设高度敏感",
                f"终值占企业价值 {tv_share*100:.0f}%（>80%）。永续增长或 WACC 的小幅变动会显著改变结论。",
                evidence_ids=evidence,
                monitoring="敏感性矩阵中心格附近波动幅度")
        return "OK", None, evidence
    record_check("valuation", _valuation)

    # ---- concentration (segment AND product views) ----
    def _concentration():
        from equitylens.api.segments_service import get_segments

        evidence: list[str] = []
        checked: list[str] = []
        for kind, kind_label in (("segment", "分部"), ("product", "产品类别")):
            seg = get_segments(store, ticker, kind=kind, frequency="annual")
            total = seg.get("total_revenue")
            if not total or kind in checked:
                continue
            checked.append(kind)
            top = max((s for s in seg["segments"] if s.get("share")), key=lambda s: s["share"] or 0)
            source_ids = [
                source["source_document_id"] for source in top.get("sources", [])
                if source.get("source_document_id")
            ]
            if top and (top["share"] or 0) > 0.45:
                # avoid double-reporting when segment already flagged
                add("structural", "HIGH" if (top["share"] or 0) > 0.6 else "MEDIUM",
                    "收入集中度偏高",
                    f"{kind_label}维度最大项「{top['name']}」占收入 {(top['share'] or 0)*100:.0f}%（>45% 阈值）。单一市场/客户/产品波动会显著影响整体。",
                    evidence_ids=source_ids,
                    monitoring="下一年度集中度变化")
                evidence.extend(source_ids)
            elif kind == "segment" and len(seg["segments"]) <= 3:
                add("structural", "LOW", "分部数量少，多元化有限",
                    f"仅 {len(seg['segments'])} 个报告分部。",
                    evidence_ids=source_ids,
                    monitoring="是否新增高增长分部")
        return "OK", None, evidence
    record_check("concentration", _concentration)

    # ---- governance / management (from M6 scorecard gaps) ----
    def _management():
        from equitylens.domain.management_score import management_scorecard

        sc = management_scorecard(store, company_id, ticker)
        if sc.get("overall_score") is None:
            add("execution", "LOW", "管理层可验证证据不足",
                "管理评分未达到规则要求的证据覆盖，战略与治理维度暂不可量化。",
                monitoring="接入更多 DEF 14A 章节与 Earnings Call 证据")
        return "OK", None, []
    record_check("management", _management)

    # severity ordering
    order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
    risks.sort(key=lambda r: (order.get(r["severity"], 3), r["category"]))
    unavailable = [check for check in checks if check["status"] != "OK"]
    completed = len(checks) - len(unavailable)
    return {
        "ticker": ticker, "generated_by": "deterministic-rules.v1",
        "risks": risks, "checks": checks,
        "coverage": {
            "total": len(checks), "completed": completed,
            "complete": not unavailable, "unavailable": unavailable,
        },
    }
