"""Deterministic risk signal engine (M7).

Risk items are generated by RULES over canonical facts, derived metrics,
segment data and valuation outputs — never by an LLM and never guessed.
Each item carries:
- category (structural/cyclical/execution/financial/regulatory/valuation/concentration)
- severity (HIGH/MEDIUM/LOW) from explicit thresholds
- evidence: fact ids / series the signal is computed from
- monitoring: the next observable that would confirm or falsify the risk
"""

from __future__ import annotations

from equitylens.metrics.engine import MetricEngine


def _series(engine, company_id: str, metric: str, freq: str = "quarterly"):
    try:
        pts = engine.compute(metric, company_id, frequency=freq)
    except ValueError:
        return []
    return pts


def _yoy_change(vals: list[float | None]) -> float | None:
    vals = [v for v in vals if v is not None]
    if len(vals) < 2 or not vals[-1]:
        return None
    return vals[-1] / vals[-2] - 1.0


def risk_signals(store, company_id: str, ticker: str) -> dict:
    engine = MetricEngine(store)
    risks: list[dict] = []

    def add(category, severity, title, desc, evidence_ids=None, monitoring=None, confidence="MEDIUM"):
        risks.append({
            "category": category, "severity": severity, "title": title, "description": desc,
            "evidence_ids": evidence_ids or [],
            "monitoring": monitoring or "下一份 10-K/10-Q 复核同一信号",
            "confidence": confidence, "generated_by": "deterministic-rules.v1",
        })

    # ---- growth / execution ----
    growth = _series(engine, company_id, "REVENUE_GROWTH_YOY")
    if len(growth) >= 3:
        recent = [p.value for p in growth[-3:] if p.value is not None]
        if len(recent) >= 2 and recent[-1] is not None:
            decel = recent[-1] - recent[-2]
            if decel < -0.05:
                add("cyclical", "MEDIUM", "收入增速明显放缓",
                    f"最近季度收入同比 {recent[-1]*100:.1f}%，较上季度 {recent[-2]*100:.1f}% 回落 {(recent[-2]-recent[-1])*100:.1f}pp。",
                    evidence_ids=[f.canonical_fact_id for f in growth[-2:] if f.canonical_fact_id],
                    monitoring="未来 2 个季度的收入同比是否企稳")
            elif recent[-1] is not None and recent[-1] < 0.03:
                add("execution", "MEDIUM", "增长动能偏弱",
                    f"最近季度收入同比仅 {recent[-1]*100:.1f}%（低于 3% 阈值）。",
                    monitoring="下季度收入同比是否回升至 3% 以上")

    # ---- profitability ----
    opm = _series(engine, company_id, "OPERATING_MARGIN")
    if len(opm) >= 5:
        vals = [p.value for p in opm[-5:] if p.value is not None]
        if len(vals) >= 3 and vals[-1] is not None and vals[0]:
            delta = vals[-1] - vals[0]
            if delta < -0.02:
                add("financial", "MEDIUM", "营业利润率走低",
                    f"营业利润率近 5 季从 {vals[0]*100:.1f}% 降至 {vals[-1]*100:.1f}%（{(vals[0]-vals[-1])*100:.1f}pp）。",
                    evidence_ids=[p.canonical_fact_id for p in opm[-1:] if p.canonical_fact_id],
                    monitoring="下季度利润率能否止跌")

    # ---- cash conversion / capital intensity ----
    ocf = _series(engine, company_id, "OPERATING_CASH_FLOW")
    capex = _series(engine, company_id, "CAPITAL_EXPENDITURES")
    if len(ocf) >= 4 and len(capex) >= 4:
        ocf_ttm = sum(p.value for p in ocf[-4:] if p.value) 
        capex_ttm = sum(p.value for p in capex[-4:] if p.value)
        if ocf_ttm and capex_ttm / ocf_ttm > 0.5:
            add("financial", "HIGH", "资本开支强度显著上升",
                f"TTM CapEx {capex_ttm/1e9:.0f}B 占 TTM 经营现金流 {ocf_ttm/1e9:.0f}B 的 {capex_ttm/ocf_ttm*100:.0f}%（>50% 阈值）。若新增资本回报不足，自由现金流转化将受压。",
                monitoring="下季度 CapEx/OCF 比例与 FCF 转化率")

    # ---- balance sheet ----
    nd = _series(engine, company_id, "NET_DEBT")
    if nd and nd[-1].value is not None:
        net_debt = nd[-1].value
        fcf_pts = _series(engine, company_id, "FCF")
        fcf_ttm = sum(p.value for p in fcf_pts[-4:] if p.value) if len(fcf_pts) >= 4 else None
        if net_debt > 0 and fcf_ttm:
            ratio = net_debt / fcf_ttm
            if ratio > 1.5:
                add("financial", "HIGH", "净债务相对自由现金流偏高",
                    f"净债务 {net_debt/1e9:.0f}B 是 TTM FCF {fcf_ttm/1e9:.0f}B 的 {ratio:.1f} 倍（>1.5x）。",
                    monitoring="下一期净债务与 FCF 比值")

    # ---- valuation risk (data-driven, no market price needed) ----
    from equitylens.valuation.service import default_valuation
    from equitylens.valuation.service import reverse_dcf

    try:
        dv = default_valuation(store, company_id, ticker)
        base_fair = dv["result"]["fair_value_per_share"]
        tv_share = dv["result"]["terminal_value_share"]
        if tv_share > 0.80:
            add("valuation", "MEDIUM", "DCF 价值对终值假设高度敏感",
                f"终值占企业价值 {tv_share*100:.0f}%（>80%）。永续增长或 WACC 的小幅变动会显著改变结论。",
                evidence_ids=["valuation_model:fcff_dcf.v1"],
                monitoring="敏感性矩阵中心格附近波动幅度")
    except Exception:
        pass

    # ---- concentration (segment AND product views) ----
    try:
        from equitylens.api.segments_service import get_segments

        checked: list[str] = []
        for kind, kind_label in (("segment", "分部"), ("product", "产品类别")):
            seg = get_segments(store, ticker, kind=kind, frequency="annual")
            total = seg.get("total_revenue")
            if not total or kind in checked:
                continue
            checked.append(kind)
            top = max((s for s in seg["segments"] if s.get("share")), key=lambda s: s["share"] or 0)
            if top and (top["share"] or 0) > 0.45:
                # avoid double-reporting when segment already flagged
                add("structural", "HIGH" if (top["share"] or 0) > 0.6 else "MEDIUM",
                    "收入集中度偏高",
                    f"{kind_label}维度最大项「{top['name']}」占收入 {(top['share'] or 0)*100:.0f}%（>45% 阈值）。单一市场/客户/产品波动会显著影响整体。",
                    evidence_ids=[f"segment:{top['name']}"],
                    monitoring="下一年度集中度变化")
            elif kind == "segment" and len(seg["segments"]) <= 3:
                add("structural", "LOW", "分部数量少，多元化有限",
                    f"仅 {len(seg['segments'])} 个报告分部。",
                    monitoring="是否新增高增长分部")
    except Exception:
        pass

    # ---- governance / management (from M6 scorecard gaps) ----
    try:
        from equitylens.domain.management_score import management_scorecard

        sc = management_scorecard(store, company_id, ticker)
        if sc.get("overall_score") is None:
            add("execution", "LOW", "管理层可验证证据不足",
                f"管理评分证据覆盖率 {sc['coverage']*100:.0f}%（<{sc['minimum_coverage']*100:.0f}%），战略/治理维度暂不可量化。",
                monitoring="接入更多 DEF 14A 章节与 Earnings Call 证据")
    except Exception:
        pass

    # severity ordering
    order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
    risks.sort(key=lambda r: (order.get(r["severity"], 3), r["category"]))
    return {"ticker": ticker, "generated_by": "deterministic-rules.v1", "risks": risks}
